# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  format-all:
    cmds:
      - terraform fmt -recursive
      - terragrunt hclfmt

  init-all:
    cmds:
      - find . -not -path '*/.terragrunt-cache/*' -type f -name terragrunt.hcl -execdir terragrunt init -input=false \;